feat: use edgee cli action

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -16,6 +16,9 @@ jobs:
             - name: Checkout
               uses: actions/checkout@v4
 
+            - name: Install edgee
+              uses: edgee-cloud/install-edgee-cli@v0.1.0
+
             - name: "Set up C component build system"
               run: |
                   apt-get update
@@ -29,7 +32,16 @@ jobs:
             - name: Install wasm tooling
               run: CC=clang cargo install wit-bindgen-cli wasm-tools --locked
 
+            - name: Build
+              run: |
+                  edgee components build
+
+            - name: Verify .wasm file exists
+              run: |
+                  if [ ! -f "./dc_component.wasm" ]; then
+                    echo "❌ Error: dc_component.wasm not found" >&2
+                    exit 1
+                  fi
+
             - name: Build component
               run: |
-                  make setup
-                  make build-no-edgee
